language: python
python:
  - "3.6"
# command to install dependencies
install: 
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
    # Useful for debugging any issues with conda
  - conda info -a
  # Replace dep1 dep2 ... with your dependencies
  - conda create -q -n test python=$TRAVIS_PYTHON_VERSION
  - source activate test
  - conda install -y -q -c conda-forge -c cmutel -c haasad brightway2 jupyter
  - pip install -e .
  - pip install -r travis-requirements.txt
  - pip list

# command to run tests
script: cd tests; pytest --cov=lcopt

after_success: coveralls